#lib/elixir_graphql_mysql_web/endpoint.ex
defmodule ElixirGraphqlMysqlWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :elixir_graphql_mysql

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_elixir_graphql_mysql_key",
    signing_salt: "i1DQp83y",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.

  plug Plug.Parsers,
    parsers: [
      :urlencoded,
      :multipart, # Keep this
      :json,
      Absinthe.Plug.Parser # ADD THIS LINE
    ],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.Static,
    at: "/",
    from: :elixir_graphql_mysql,
    gzip: false,
    only: ~w(assets fonts images favicon.ico robots.txt users products assets) 
#    only: ~w(css fonts images js favicon.ico robots.txt index.html)    
#    gzip: not code_reloading?,
#    only: ElixirGraphqlMysqlWeb.static_paths(),
#    raise_on_missing_only: code_reloading?




  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :elixir_graphql_mysql
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug CORSPlug, [
    origin: ["http://localhost:5173", "http://127.0.0.1:5173"],
    headers: ["Authorization", "Content-Type", "Apollo-Require-Preflight" | CORSPlug.defaults()[:headers]]
  ]
  plug ElixirGraphqlMysqlWeb.Router
end
